<?php
session_start();

// Type = Text
header("Content-type: text/plain");

// Detect (and create) session
if(isset($_SESSION["twtxt"])==false){
  $_SESSION["twtxt"] = "# Generated by Picopub";
}
echo $_SESSION["twtxt"];
?>
